### PR TITLE
Add declaration file for theories

### PR DESCRIPTION
**Pull request by elevatebart**
In order for jasmine theories to be well typed and documented in typescript, It would be awesome to ave a declaration file in there.

### CODE REVIEW

**Comment by hypesystem** [comment]
Hey! This looks great :-)

Have you tested that it works? I have no idea how TypeScript declaration files work, so I am kind of relying on your knowledge here :-)

**Comment by hypesystem** [comment]
(Oh, as far as I can see in the docs, you need to expose the file in the `types` field in `package.json`: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html )

**Comment by elevatebart** [comment]
I added the ```"types": "index.d.ts"``` value to the package.json. It was actually unneccessary and if you deem necessary to remove it, just go ahead.

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

**Comment by elevatebart** [comment]
I as well added some live documentation so that if you use this library in vscode or webstorm, live doc would pop-up as autocomplete kicks in.

intellisense

**Comment by hypesystem** [comment]
This looks super! Thank you so much for the work :-)

I'm just going to change the version bump to a patch bump (no new functionality in this one) and then publish :)

**Pull request merged**
